{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.kaidl",
    "module": "kaidl",
    "version": "1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kaidl-1.15.jar",
          "url": "kaidl-1.15.jar",
          "size": 59141,
          "sha512": "31584c09e214c14d11603284c82351e6112be8a1a34721bedf6ce99b7e3076f4bc30ea44993f35681ddc9aa4b17c17d376db3537b7a4e6b39793dafc8422bff0",
          "sha256": "de6dff2bc695d79f809c2d0b6c2c89ed630d2b834d407f7cd1db3000c0812b61",
          "sha1": "4ca900df42dbf7b501a4cc869f8e9d46e1baebbf",
          "md5": "65b0c547de929ba9b20834716ba2479d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.5.30-1.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kaidl-1.15.jar",
          "url": "kaidl-1.15.jar",
          "size": 59141,
          "sha512": "31584c09e214c14d11603284c82351e6112be8a1a34721bedf6ce99b7e3076f4bc30ea44993f35681ddc9aa4b17c17d376db3537b7a4e6b39793dafc8422bff0",
          "sha256": "de6dff2bc695d79f809c2d0b6c2c89ed630d2b834d407f7cd1db3000c0812b61",
          "sha1": "4ca900df42dbf7b501a4cc869f8e9d46e1baebbf",
          "md5": "65b0c547de929ba9b20834716ba2479d"
        }
      ]
    }
  ]
}
